### PR TITLE
SBC/README: Add description of jumper settings

### PR DESCRIPTION
**Pull request by 0cjs**
Per issue #9.

### CODE REVIEW

**Comment by 0cjs** [comment]
Are there any issues with this preventing it from being merged?

**Comment by 0cjs** [comment]
@tebl Are there any issues with this preventing it from being merged?

**Comment by tebl** [comment]
It's just been an issue of time, I'm in the process of moving and currently
I'm not even sure where my laptop is. Hoping to find some more time this
summer to do a proper review of the documentation.

tir. 19. mai 2020, 12:55 skrev Curt J. Sampson <notifications@github.com>:

**Comment by 0cjs** [comment]
Ok, no problem. If in the meantime you want to review this by just using the web interface to view [the diff](https://github.com/tebl/RC6502-Apple-1-Replica/pull/10/commits/f85c1148b2b10fba55cf412a72f428cd2cc6bcfc) and [the rendered version](https://github.com/tebl/RC6502-Apple-1-Replica/blob/f85c1148b2b10fba55cf412a72f428cd2cc6bcfc/RC6502%20Apple%201%20SBC/README.md#jumper-settings) and asking me for changes (even trivial ones), I'm happy to do that. However, I've been working with the PDF export of the schematic because at the moment I'm unable to load the `.sch` file into KiCAD. (I'll have to work out at some point where my issue is with this.)

**Comment by 0cjs** [comment]
Oh, good catch! I seem to have that error on the brain; I "fixed" that with bodge wires when building my SBC, too, which of course didn't work until I unfixed it.

I've pushed up a FIXUP commit so you can easily see the diff; I will squash (`fixup` in `git rebase -i`, actually) the two commits together after you've reviewed it. (Unfortunately GitHub doesn't let me change this PR to "not ready to merge" state, so be careful not to merge until I've squashed. :-))

**Pull request merged**
